server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:./data/app_db;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=TRUE;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl_auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  H2:
    console.enabled: true
# added for actuator endpoints
management:
  endpoint:
    info:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"